name: Smart Contracts CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: gateway-contract

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: Build Soroban contracts
      run: cargo build --workspace --target wasm32-unknown-unknown --release --verbose

    - name: Run Cargo tests
      run: cargo test --workspace --all-features --verbose
